import { 
  LayoutDashboard, 
  Bird, 
  Warehouse, 
  Package, 
  Users, 
  ShoppingCart, 
  Receipt,
  DollarSign, 
  Settings,
  Tag,
  ShieldCheck,
  ClipboardList,
  MessageSquare,
  Truck,
  Ruler
} from 'lucide-react'

export const navigationItems = [
  { name: 'Dashboard', href: '/', icon: LayoutDashboard },
  { name: 'Lotes', href: '/lotes', icon: Bird },
  { name: 'Planificación', href: '/planificacion', icon: ClipboardList },
  { name: 'Chat con IA', href: '/chat', icon: MessageSquare },
  { name: 'Galpones', href: '/galpones', icon: Warehouse },
  { name: 'Inventario', href: '/inventario', icon: Package },
  { name: 'Categorías', href: '/categorias', icon: Tag },
  { name: 'Unidades', href: '/unidades-medida', icon: Ruler },
  { name: 'Productos', href: '/productos', icon: Package },
  { name: 'Ventas', href: '/ventas', icon: ShoppingCart },
  { name: 'Gastos', href: '/gastos', icon: Receipt },
  { name: 'Finanzas', href: '/finanzas', icon: DollarSign },
  { name: 'Sanidad', href: '/sanidad', icon: ShieldCheck },
  { name: 'Plantillas', href: '/plantillas', icon: ClipboardList },
  { name: 'Proveedores', href: '/proveedores', icon: Truck },
  { name: 'Clientes', href: '/clientes', icon: Users },
  { name: 'Auditoría', href: '/auditoria', icon: ClipboardList },
  { name: 'Usuarios', href: '/usuarios', icon: Users },
  { name: 'Configuración', href: '/configuracion', icon: Settings },
]
