// <auto-generated />
using System;
using System.Collections.Generic;
using GalponERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GalponERP.Infrastructure.Migrations
{
    [DbContext(typeof(GalponDbContext))]
    [Migration("20260419044624_AddFormulasModule")]
    partial class AddFormulasModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GalponERP.Domain.Entities.ActividadPlantilla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadRecomendada")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DiaDeAplicacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlantillaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductoIdRecomendado")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoActividad")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaId");

                    b.HasIndex("ProductoIdRecomendado");

                    b.ToTable("ActividadesPlantillas", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetallesJSON")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaLogs", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.CalendarioSanitario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadRecomendada")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("DescripcionTratamiento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DiaDeAplicacion")
                        .HasColumnType("integer");

                    b.Property<bool>("EsManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Justificacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductoIdRecomendado")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Otros");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoIdRecomendado");

                    b.ToTable("CalendarioSanitario", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.CategoriaProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CategoriasProductos");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.CompraInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nota")
                        .HasColumnType("text");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioIdRegistro")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Total", "GalponERP.Domain.Entities.CompraInventario.Total#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalCompra");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPagado", "GalponERP.Domain.Entities.CompraInventario.TotalPagado#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalPagado");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ComprasInventario", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.ConfiguracionSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MonedaPorDefecto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionSistema", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ResumenActual")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UltimoIndiceMensajeResumido")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Conversaciones", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Formula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Formulas", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.FormulaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadPorBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FormulaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormulaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("FormulaDetalles", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Galpon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Galpones", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.GastoOperativo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoGasto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Monto", "GalponERP.Domain.Entities.GastoOperativo.Monto#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Monto");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GalponId");

                    b.HasIndex("LoteId");

                    b.ToTable("GastosOperativos", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.IntencionPendiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FuncionNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ParametrosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PluginNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Procesada")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("IntencionesPendientes");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("FCRFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GalponId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JustificacionCancelacion")
                        .HasColumnType("text");

                    b.Property<int>("MortalidadAcumulada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PollosVendidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("PorcentajeMortalidadFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CostoTotalFinal", "GalponERP.Domain.Entities.Lote.CostoTotalFinal#Moneda", b1 =>
                        {
                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CostoTotalFinal");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CostoUnitarioPollito", "GalponERP.Domain.Entities.Lote.CostoUnitarioPollito#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CostoUnitarioPollito");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UtilidadNetaFinal", "GalponERP.Domain.Entities.Lote.UtilidadNetaFinal#Moneda", b1 =>
                        {
                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("UtilidadNetaFinal");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GalponId");

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.MensajeChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.ToTable("MensajesChat", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.MortalidadDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadBajas")
                        .HasColumnType("integer");

                    b.Property<string>("Causa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Mortalidades", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("CostoTotal");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Justificacion")
                        .HasColumnType("text");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoUnitarioHistorico")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("Fecha");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoId");

                    b.ToTable("MovimientosInventario", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.OrdenCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioIdRegistro")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Total", "GalponERP.Domain.Entities.OrdenCompra.Total#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalOrden");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesCompra", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.OrdenCompraItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrdenCompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PrecioUnitario", "GalponERP.Domain.Entities.OrdenCompraItem.PrecioUnitario#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PrecioUnitario");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Total", "GalponERP.Domain.Entities.OrdenCompraItem.Total#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalItem");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesCompraItems", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PagoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Monto", "GalponERP.Domain.Entities.PagoCompra.Monto#Moneda", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Monto")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Monto");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("FechaPago");

                    b.ToTable("PagosCompras", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PagoVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("Monto");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaPago");

                    b.HasIndex("VentaId");

                    b.ToTable("PagosVentas", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PesajeLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadMuestreada")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoPromedioGramos")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("PesajesLote");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PlantillaSanitaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PlantillasSanitarias", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostoUnitarioActual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("StockActualKg")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("UmbralMinimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProductoId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NitRuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NitRuc")
                        .IsUnique();

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.RegistroBienestar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CloroPpm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ConsumoAgua")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Humedad")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RegistroBienestar");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoVinculacion")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaExpiracionCodigo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Profesion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhatsAppNumero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique()
                        .HasFilter("\"Telefono\" IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadPollos")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoTotalVendido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrecioPorKilo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("PrecioPorKilo");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("TotalVenta");

                    b.Property<Guid?>("UsuarioCreacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioModificacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Fecha");

                    b.HasIndex("LoteId");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.ActividadPlantilla", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.PlantillaSanitaria", null)
                        .WithMany("Actividades")
                        .HasForeignKey("PlantillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalponERP.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoIdRecomendado")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.CalendarioSanitario", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalponERP.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoIdRecomendado")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.CompraInventario", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.FormulaDetalle", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Formula", "Formula")
                        .WithMany("Detalles")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalponERP.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formula");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.GastoOperativo", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Galpon", null)
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalponERP.Domain.Entities.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Lote", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Galpon", "Galpon")
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Galpon");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.MensajeChat", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.MortalidadDiaria", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.CompraInventario", null)
                        .WithMany()
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GalponERP.Domain.Entities.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GalponERP.Domain.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.OrdenCompra", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.OrdenCompraItem", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.OrdenCompra", null)
                        .WithMany("Items")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalponERP.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PagoCompra", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.CompraInventario", null)
                        .WithMany("Pagos")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PagoVenta", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Venta", null)
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PesajeLote", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Lote", null)
                        .WithMany("Pesajes")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Producto", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.CategoriaProducto", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalponERP.Domain.Entities.UnidadMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Venta", b =>
                {
                    b.HasOne("GalponERP.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GalponERP.Domain.Entities.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.CompraInventario", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Formula", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Lote", b =>
                {
                    b.Navigation("Pesajes");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.OrdenCompra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.PlantillaSanitaria", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("GalponERP.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
